### ISSUE TITLE
Doesn't pick up name when when scope variables are used

### ISSUE THREAD

**Issue by cmacdonnacha** [thomasmalm/gfl-text-avatar#1]
Using the text avatar like this:
![image](https://cloud.githubusercontent.com/assets/9777763/14812981/7ed22266-0b97-11e6-9953-ff6e1e77b166.png)

Doesn't seem to work:
![image](https://cloud.githubusercontent.com/assets/9777763/14813052/d24b282a-0b97-11e6-96b7-017b526ced20.png)

**Comment by thomasmalm** [comment]
Please try the new 0.2.0 version with support for expressions.

**Comment by cmacdonnacha** [comment]
Thanks for the prompt fix. Could you update the bower package to 0.2.0?

**Comment by thomasmalm** [comment]
The v0.2.0 git tag is available (bower version is deprecated), so just update your package and you should get the 0.2.0 version.

**Comment by cmacdonnacha** [comment]
Thanks. So you can't install this plugin via bower anymore is it?

**Comment by thomasmalm** [comment]
Yes you can, just run `bower update gfl-text-avatar` to update or `bower install gfl-text-avatar --save-dev` to install.

**Comment by cmacdonnacha** [comment]
Ah ok thanks! Just wondering what you mean by "bower version is deprecated"? 

Great work on this directive by the way. You should try sharing it on reddit subreddits [/r/webdev](https://www.reddit.com/r/webdev) and [/r/angularjs](https://www.reddit.com/r/angularjs)

**Comment by thomasmalm** [comment]
See version under https://github.com/bower/spec/blob/master/json.md

**Comment by cmacdonnacha** [comment]
Ah yes sorry, what I meant was to just update the package itself to 0.2.0 which you had already done. Thanks!

**Comment by cmacdonnacha** [comment]
@thomasmalm It may be a good idea to update your **packages.json** file to 0.2.0 so that people know which version they have installed just by looking at the file :-)
